# Generated by Django 3.2.8 on 2021-11-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_userprofile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='is_key_skill',
            field=models.BooleanField(default=False),
        ),
    ]
