# Generated by Django 3.2.8 on 2021-11-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_skill_is_key_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='is_key_skill',
            field=models.BooleanField(default=True),
        ),
    ]
